### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by roydenrego** [jonasbleyl/pictorial#3]
Hello, this seems like a great library but there seems to be no documentation on how to use this.
I have been looking around and I really want to use this in my project, it would be great if there was documentation on Installation and Usage.

**Comment by jonasbleyl** [comment]
Hi,

This isn't a library so there isn't any documentation that I can provide. It's simply and app that intercepts certain HTTP requests and loads them in an overlay using a service. It shouldn't be too hard to figure out how to incorporate into your own project. Keep in mind that it is licensed under GPL.
